// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTest = "test"

// Test mapped from table <test>
type Test struct {
	ID       int32  `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	Name     string `gorm:"column:name;type:text;not null" json:"name"`
	Archived bool   `gorm:"column:archived;type:boolean;not null" json:"archived"`
}

// TableName Test's table name
func (*Test) TableName() string {
	return TableNameTest
}
