// Code generated by hertz generator. Modified for manual conversation_id support (no hz/thriftgo regeneration).

package api

import (
	"context"
	"encoding/json"
	"io"

	api "github.com/FantasyRL/go-mcp-demo/api/model/api"
	"github.com/FantasyRL/go-mcp-demo/api/pack"
	"github.com/FantasyRL/go-mcp-demo/internal/host/application"
	"github.com/cloudwego/hertz/pkg/app"
	consts "github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/cloudwego/hertz/pkg/protocol/sse"
)

// Chat .
// 手工补丁要点：conversation_id 从 query 或 form 中读取（因为当前生成的模型无该字段）。
// @router /api/v1/chat [POST]
func Chat(ctx context.Context, c *app.RequestContext) {
	var req api.ChatRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 可选图片读取（用于非流式聊天）
	var imageData []byte
	if file, err := c.FormFile("image"); err == nil && file != nil {
		src, err := file.Open()
		if err != nil {
			pack.RespError(c, err)
			return
		}
		defer src.Close()
		data, err := io.ReadAll(src)
		if err != nil {
			pack.RespError(c, err)
			return
		}
		imageData = data
	}

	// conversation_id 兼容读取
	convID := c.Query("conversation_id")
	if convID == "" {
		convID = c.PostForm("conversation_id")
	}

	resp := new(api.ChatResponse)
	const userID = int64(1) // TODO: 接入鉴权后替换真实 userID

	msg, err := application.NewHost(ctx, clientSet).ChatWithConversation(userID, convID, req.Message, imageData)
	if err != nil {
		pack.RespError(c, err)
		return
	}
	resp.Response = msg
	// 当前生成的 ChatResponse 模型没有 ConversationID 字段，这里不回写 convID。
	pack.RespData(c, resp)
}

// ChatSSE .
// 手工补丁要点：不读取 imageData（避免未使用编译错误）。
// conversation_id 从 query 或 form 中读取，仅用于内存历史上下文（当前未持久化流式历史）。
// @router /api/v1/chat/sse [GET]
func ChatSSE(ctx context.Context, c *app.RequestContext) {
	var req api.ChatSSEHandlerRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 兼容读取 conversation_id
	convID := c.Query("conversation_id")
	if convID == "" {
		convID = c.PostForm("conversation_id")
	}

	w := sse.NewWriter(c)
	defer w.Close()

	emit := func(_ string, v any) error {
		switch x := v.(type) {
		case string:
			return w.WriteEvent("", "", []byte(x))
		case json.RawMessage:
			return w.WriteEvent("", "", x)
		default:
			b, _ := json.Marshal(v)
			return w.WriteEvent("", "", b)
		}
	}

	// 流式聊天（当前未持久化流式历史，可在应用层扩展）
	if err := application.NewHost(ctx, clientSet).StreamChatWithConversation(ctx, 1, convID, req.Message, emit); err != nil {
		_ = emit("error", map[string]any{"error": err.Error()})
		return
	}
}

// 说明：如果你的生成模型未包含历史相关结构体/接口，请使用手工版 handler（conversation_history_manual.go）并在 main.go 手工注册路由。
// 这里不再定义 GetConversationHistory，避免与手工版或生成版重复。

// Template .
// @router /api/v1/template [POST]
func Template(ctx context.Context, c *app.RequestContext) {
	var req api.TemplateRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := new(api.TemplateResponse)
	u, err := application.NewHost(ctx, clientSet).TemplateLogic(&req)
	if err != nil {
		pack.RespError(c, err)
		return
	}
	resp.User = pack.BuildUserResp(u)
	pack.RespData(c, resp)
}

// SummarizeConversation .
// @router /api/v1/conversation/summarize [POST]
func SummarizeConversation(ctx context.Context, c *app.RequestContext) {
	var req api.SummarizeConversationRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	result, err := application.NewHost(ctx, clientSet).SummarizeConversation(req.ConversationID)
	if err != nil {
		pack.RespError(c, err)
		return
	}
	resp := &api.SummarizeConversationResponse{
		Summary:       result.Summary,
		Tags:          result.Tags,
		ToolCallsJSON: result.ToolCallsJSON,
		Notes:         result.Notes,
	}
	pack.RespData(c, resp)
}

// GetLoginData .
// @router /api/v1/user/login [POST]
func GetLoginData(ctx context.Context, c *app.RequestContext) {
	var req api.GetLoginDataRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := new(api.GetLoginDataResponse)
	loginData, err := application.NewHost(ctx, clientSet).Login(req.StuID, req.Password)
	if err != nil {
		pack.RespError(c, err)
		return
	}
	resp.Identifier = loginData.Identifier
	resp.Cookie = loginData.Cookie
	resp.AccessToken = loginData.AccessToken
	pack.RespData(c, resp)
}

// GetUserInfo .
// @router /api/v1/user/info [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var req api.GetUserInfoRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	info, err := application.NewHost(ctx, clientSet).GetUserInfo()
	if err != nil {
		pack.RespError(c, err)
		return
	}
	pack.RespData(c, info)
}
